Allow plotting service to go find files
fiaisis/plotting-service pull request #212
Opened 2024-10-22 10:18 UTC by Pasarus

Closes None, fixes an issue in staging and prod

## Description
Better handles the finding file race condition on staging, the previous PR had an issue where it relied on a hidden race condition that was exposed by some seemingly basic refactoring in the code to fix the e2e tests. This race condition is now handled much better.

2024-10-22 13:19 UTC, Dagonite approved these changes
LGTM code-wise.

2024-10-28 14:29 UTC, Pasarus commented
Issue made to reimplement the commented out workflow:
[#217](https://github.com/fiaisis/plotting-service/issues/217)

2024-10-28 15:20 UTC, Dagonite requested changes

2024-10-28 15:20 UTC, Dagonite commented on .github/workflows/test.yml
> +#          path: data-viewer/cypress/screenshots
Commented out YML code instead of deleted. This right?

2024-10-28 15:20 UTC, Dagonite commented on data-viewer/src/components/NexusViewer.tsx
> +    console.log("Token set as: " + loadedToken)
Should this log be here?

2024-10-28 15:22 UTC, Dagonite commented on .github/workflows/test.yml
> +#          path: data-viewer/cypress/screenshots
Oh, just seen above.

2024-10-28 15:24 UTC, Pasarus commented on data-viewer/src/components/NexusViewer.tsx
> +    console.log("Token set as: " + loadedToken)
Good catch here.

2024-10-28 15:24 UTC, Dagonite approved these changes
LGTM

2024-10-28 15:25 UTC, merged